import React, { useState, useRef } from 'react';
import { useBrands, useCreateBrand, useUpdateBrand, useDeleteBrand } from '../hooks/useApi';
import { Card, Button, Badge } from './ui';
import { Modal } from './Modal';
import { jsPDF } from 'jspdf';
import { 
  Globe, 
  Tag,
  Plus,
  Pencil,
  Trash2,
  AlertTriangle,
  Upload,
  Link as LinkIcon,
  Zap,
  Mail,
  Info,
  Download,
  Image as ImageIcon
} from 'lucide-react';
import { cn } from '../lib/utils';

export function BrandManagement() {
  const { data: brands, isLoading } = useBrands();
  const createBrand = useCreateBrand();
  const updateBrand = useUpdateBrand();
  const deleteBrand = useDeleteBrand();

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingBrand, setEditingBrand] = useState<any>(null);
  
  const [formData, setFormData] = useState<any>({
    name: '',
    color: '#6366f1',
    secondaryColor: '#f8fafc',
    logo: '',
    description: '',
    tagline: '',
    contact: { website: '', email: '', phone: '' },
    socials: { twitter: '', linkedin: '', facebook: '', instagram: '' },
    styleGuide: '',
    notes: ''
  });

  const [isDeleteModalOpen, setIsDeleteModalOpen] = useState(false);
  const [brandToDelete, setBrandToDelete] = useState<any>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleDownloadGuide = (brand: any) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(brand.color);
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.text(brand.name, 20, 25);
    
    doc.setFontSize(12);
    doc.text(brand.tagline || 'Brand Guidelines', 20, 33);
    
    // Content
    doc.setTextColor(51, 65, 85); // slate-700
    doc.setFontSize(16);
    doc.text('Brand Overview', 20, 55);
    
    doc.setFontSize(10);
    const splitDescription = doc.splitTextToSize(brand.description || 'No description available.', 170);
    doc.text(splitDescription, 20, 65);
    
    // Colors
    doc.setFontSize(16);
    doc.text('Visual Palette', 20, 95);
    
    doc.setFontSize(10);
    doc.text('Primary Color:', 20, 105);
    doc.setFillColor(brand.color);
    doc.rect(50, 101, 10, 5, 'F');
    doc.text(brand.color, 65, 105);
    
    doc.text('Secondary Color:', 20, 115);
    doc.setFillColor(brand.secondaryColor);
    doc.rect(50, 111, 10, 5, 'F');
    doc.text(brand.secondaryColor, 65, 115);
    
    // Business Presence
    doc.setFontSize(16);
    doc.text('Business Presence', 20, 135);
    
    doc.setFontSize(10);
    doc.text(`Website: ${brand.contact?.website || 'N/A'}`, 20, 145);
    doc.text(`Email: ${brand.contact?.email || 'N/A'}`, 20, 152);
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text('Generated by Brivo Brand Workstation', 20, 280);
    
    doc.save(`${brand.name}-brand-guide.pdf`);
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setFormData({ ...formData, logo: reader.result as string });
      };
      reader.readAsDataURL(file);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (editingBrand) {
      updateBrand.mutate({ id: editingBrand._id, data: formData }, {
        onSuccess: () => {
          setIsModalOpen(false);
          setEditingBrand(null);
          resetForm();
        }
      });
    } else {
      createBrand.mutate(formData, {
        onSuccess: () => {
          setIsModalOpen(false);
          resetForm();
        }
      });
    }
  };

  const resetForm = () => {
    setFormData({
      name: '',
      color: '#6366f1',
      secondaryColor: '#f8fafc',
      logo: '',
      description: '',
      tagline: '',
      contact: { website: '', email: '', phone: '' },
      socials: { twitter: '', linkedin: '', facebook: '', instagram: '' },
      styleGuide: '',
      notes: ''
    });
  };

  const handleEdit = (brand: any) => {
    setEditingBrand(brand);
    setFormData({
      name: brand.name || '',
      color: brand.color || '#6366f1',
      secondaryColor: brand.secondaryColor || '#f8fafc',
      logo: brand.logo || '',
      description: brand.description || '',
      tagline: brand.tagline || '',
      contact: brand.contact || { website: '', email: '', phone: '' },
      socials: brand.socials || { twitter: '', linkedin: '', facebook: '', instagram: '' },
      styleGuide: brand.styleGuide || '',
      notes: brand.notes || ''
    });
    setIsModalOpen(true);
  };

  const handleCreate = () => {
    setEditingBrand(null);
    resetForm();
    setIsModalOpen(true);
  };

  if (isLoading) return <div className="p-8 text-center text-slate-500 italic">Preparing your brand assets...</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="space-y-1">
          <h3 className="text-xl font-black uppercase tracking-tight text-slate-900 leading-none">Brand Identities</h3>
          <p className="text-xs text-slate-500 font-medium text-[11px]">Manage your company's growing portfolio of brands.</p>
        </div>
        <Button onClick={handleCreate} size="sm" className="rounded-xl font-bold">
          <Plus className="mr-2 h-4 w-4" /> Add Brand
        </Button>
      </div>

      <div className="grid gap-6 sm:grid-cols-2">
        {brands?.map((brand: any) => (
          <Card key={brand._id} className="p-0 overflow-hidden flex flex-col group group/brand hover:shadow-2xl hover:shadow-primary/5 transition-all border-slate-200/60">
            <div className="h-24 relative overflow-hidden" style={{ backgroundColor: brand.color }}>
              <div className="absolute inset-0 bg-gradient-to-br from-black/20 to-transparent" />
              {brand.logo && (
                <div className="absolute -bottom-6 left-6 h-16 w-16 rounded-2xl bg-white p-2 shadow-xl border border-slate-100 flex items-center justify-center">
                  <img src={brand.logo} alt={brand.name} className="max-h-full max-w-full object-contain" referrerPolicy="no-referrer" />
                </div>
              )}
              <div className="absolute top-4 right-4 flex gap-1 opacity-0 group-hover:opacity-100 transition-all transform translate-y-2 group-hover:translate-y-0">
                <Button 
                  variant="secondary" 
                  size="icon" 
                  onClick={() => handleDownloadGuide(brand)} 
                  className="h-8 w-8 bg-white/90 backdrop-blur-sm border-none shadow-lg text-primary hover:text-primary-dark"
                  title="Download Brand Guide"
                >
                  <Download className="h-3.5 w-3.5" />
                </Button>
                <Button variant="secondary" size="icon" onClick={() => handleEdit(brand)} className="h-8 w-8 bg-white/90 backdrop-blur-sm border-none shadow-lg">
                  <Pencil className="h-3.5 w-3.5" />
                </Button>
                <Button 
                  variant="secondary" 
                  size="icon" 
                  onClick={() => {
                    setBrandToDelete(brand);
                    setIsDeleteModalOpen(true);
                  }} 
                  className="h-8 w-8 bg-white/90 backdrop-blur-sm border-none shadow-lg text-red-500 hover:text-red-600"
                >
                  <Trash2 className="h-3.5 w-3.5" />
                </Button>
              </div>
            </div>
            
            <div className="p-6 pt-10 space-y-4 flex-1 text-slate-900">
              <div>
                <h4 className="text-lg font-black leading-tight">{brand.name}</h4>
                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em]">{brand.tagline || 'No tagline set'}</p>
              </div>
              
              <p className="text-xs text-slate-500 line-clamp-2 leading-relaxed min-h-[32px]">
                {brand.description || 'Provide a brief overview of this brand identity.'}
              </p>

              <div className="flex flex-wrap gap-2 pt-2">
                 {brand.contact?.website && (
                   <a href={brand.contact.website} target="_blank" rel="noopener noreferrer" className="p-2 rounded-lg bg-slate-50 text-slate-400 hover:text-primary transition-colors">
                     <Globe className="h-3.5 w-3.5" />
                   </a>
                 )}
                 {brand.contact?.email && (
                   <a href={`mailto:${brand.contact.email}`} className="p-2 rounded-lg bg-slate-50 text-slate-400 hover:text-primary transition-colors">
                     <Mail className="h-3.5 w-3.5" />
                   </a>
                 )}
                 <div className="ml-auto flex items-center gap-2">
                    <div className="h-3 w-3 rounded-full border border-white shadow-sm" style={{ backgroundColor: brand.color }} />
                    <div className="h-3 w-3 rounded-full border border-white shadow-sm" style={{ backgroundColor: brand.secondaryColor }} />
                 </div>
              </div>
            </div>
          </Card>
        ))}
      </div>

      <Modal 
        isOpen={isModalOpen} 
        onClose={() => {
          setIsModalOpen(false);
          setEditingBrand(null);
        }} 
        title={editingBrand ? "Polish Brand Identity" : "Launch New Brand"}
        className="max-w-4xl"
      >
        <div className="grid lg:grid-cols-[1fr_320px] gap-8">
          <form onSubmit={handleSubmit} className="space-y-8 max-h-[70vh] overflow-y-auto pr-4 scrollbar-hide">
            {/* Core Info */}
            <div className="space-y-4">
               <h4 className="text-[10px] font-black uppercase tracking-widest text-slate-400 border-b border-slate-100 pb-2">Core Identity</h4>
               <div className="grid gap-4 sm:grid-cols-2">
                 <div className="sm:col-span-2 space-y-2">
                   <label className="text-xs font-bold uppercase text-slate-500">Official Brand Name <span className="text-red-500">*</span></label>
                   <input 
                     type="text" 
                     required
                     className="w-full rounded-xl border border-slate-200 p-3 text-sm focus:ring-2 focus:ring-primary/20 bg-slate-50/50" 
                     placeholder="e.g. Nike" 
                     value={formData.name}
                     onChange={e => setFormData({ ...formData, name: e.target.value })}
                   />
                 </div>
                 <div className="space-y-2">
                   <label className="text-xs font-bold uppercase text-slate-500">Tagline</label>
                   <input 
                     type="text" 
                     className="w-full rounded-xl border border-slate-200 p-3 text-sm focus:ring-2 focus:ring-primary/20 bg-slate-50/50" 
                     placeholder="Just Do It" 
                     value={formData.tagline}
                     onChange={e => setFormData({ ...formData, tagline: e.target.value })}
                   />
                 </div>
                 <div className="space-y-2">
                   <label className="text-xs font-bold uppercase text-slate-500">Style Guide Link</label>
                   <div className="relative">
                      <LinkIcon className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-400" />
                      <input 
                        type="url" 
                        className="w-full rounded-xl border border-slate-200 p-3 pl-9 text-sm focus:ring-2 focus:ring-primary/20 bg-slate-50/50" 
                        placeholder="https://..." 
                        value={formData.styleGuide}
                        onChange={e => setFormData({ ...formData, styleGuide: e.target.value })}
                      />
                   </div>
                 </div>
                 <div className="sm:col-span-2 space-y-2">
                   <label className="text-xs font-bold uppercase text-slate-500">Brand Overview</label>
                   <textarea 
                     className="w-full rounded-xl border border-slate-200 p-3 text-sm focus:ring-2 focus:ring-primary/20 bg-slate-50/50 min-h-[80px]" 
                     placeholder="Briefly describe the brand's mission and personality..." 
                     value={formData.description}
                     onChange={e => setFormData({ ...formData, description: e.target.value })}
                   />
                 </div>
               </div>
            </div>

            {/* Visuals */}
            <div className="space-y-4">
               <h4 className="text-[10px] font-black uppercase tracking-widest text-slate-400 border-b border-slate-100 pb-2">Visual Palette</h4>
               <div className="grid gap-6 sm:grid-cols-2">
                 <div className="space-y-3">
                   <label className="text-xs font-bold uppercase text-slate-500">Primary Color</label>
                   <div className="flex gap-2">
                      <input 
                        type="color" 
                        className="h-11 w-11 rounded-xl border border-slate-200 p-1 cursor-pointer" 
                        value={formData.color}
                        onChange={e => setFormData({ ...formData, color: e.target.value })}
                      />
                      <input 
                        type="text" 
                        className="flex-1 rounded-xl border border-slate-200 p-2.5 text-xs font-mono uppercase bg-slate-50/50"
                        value={formData.color}
                        onChange={e => setFormData({ ...formData, color: e.target.value })}
                      />
                   </div>
                 </div>
                 <div className="space-y-3">
                   <label className="text-xs font-bold uppercase text-slate-500">Secondary Color</label>
                   <div className="flex gap-2">
                      <input 
                        type="color" 
                        className="h-11 w-11 rounded-xl border border-slate-200 p-1 cursor-pointer" 
                        value={formData.secondaryColor}
                        onChange={e => setFormData({ ...formData, secondaryColor: e.target.value })}
                      />
                      <input 
                        type="text" 
                        className="flex-1 rounded-xl border border-slate-200 p-2.5 text-xs font-mono uppercase bg-slate-50/50"
                        value={formData.secondaryColor}
                        onChange={e => setFormData({ ...formData, secondaryColor: e.target.value })}
                      />
                   </div>
                 </div>
                 <div className="sm:col-span-2 space-y-3">
                   <div className="flex items-center justify-between">
                     <label className="text-xs font-bold uppercase text-slate-500">Brand Logo</label>
                     <p className="text-[10px] text-slate-400 italic">SVG, PNG, JPG (Max 2MB)</p>
                   </div>
                   <div className="grid gap-3 sm:grid-cols-[1fr_auto]">
                     <div className="space-y-3">
                       <div className="flex gap-3">
                         <div className="flex-1 relative">
                            <LinkIcon className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-400" />
                            <input 
                              type="text" 
                              className="w-full rounded-xl border border-slate-200 p-3 pl-9 text-sm focus:ring-2 focus:ring-primary/20 bg-slate-50/50" 
                              placeholder="https://logo-url.png" 
                              value={formData.logo}
                              onChange={e => setFormData({ ...formData, logo: e.target.value })}
                            />
                         </div>
                         <Button 
                            type="button"
                            variant="outline"
                            className="rounded-xl px-4"
                            onClick={() => fileInputRef.current?.click()}
                          >
                           <Upload className="h-4 w-4 mr-2" />
                           Upload File
                         </Button>
                         <input 
                           type="file"
                           ref={fileInputRef}
                           className="hidden"
                           accept="image/*"
                           onChange={handleFileUpload}
                         />
                       </div>
                     </div>
                     
                     {formData.logo && (
                       <div className="h-11 w-11 rounded-xl bg-white border border-slate-200 p-1 flex items-center justify-center shrink-0">
                         <img src={formData.logo} alt="Logo" className="max-h-full max-w-full object-contain" referrerPolicy="no-referrer" />
                       </div>
                     )}
                   </div>
                 </div>
               </div>
            </div>

            {/* Contact & Socials */}
            <div className="space-y-4">
               <h4 className="text-[10px] font-black uppercase tracking-widest text-slate-400 border-b border-slate-100 pb-2">Business Presence</h4>
               <div className="grid gap-4 sm:grid-cols-2">
                 <div className="space-y-2">
                   <label className="text-xs font-bold uppercase text-slate-500">Website</label>
                   <input 
                     type="url" 
                     className="w-full rounded-xl border border-slate-200 p-3 text-sm focus:ring-2 focus:ring-primary/20 bg-slate-50/50" 
                     placeholder="nike.com" 
                     value={formData.contact.website}
                     onChange={e => setFormData({ ...formData, contact: { ...formData.contact, website: e.target.value } })}
                   />
                 </div>
                 <div className="space-y-2">
                   <label className="text-xs font-bold uppercase text-slate-500">Public Email</label>
                   <input 
                     type="email" 
                     className="w-full rounded-xl border border-slate-200 p-3 text-sm focus:ring-2 focus:ring-primary/20 bg-slate-50/50" 
                     placeholder="media@brand.com" 
                     value={formData.contact.email}
                     onChange={e => setFormData({ ...formData, contact: { ...formData.contact, email: e.target.value } })}
                   />
                 </div>
                 <div className="space-y-2">
                   <label className="text-xs font-bold uppercase text-slate-500">Twitter (X)</label>
                   <input 
                     type="text" 
                     className="w-full rounded-xl border border-slate-200 p-3 text-sm focus:ring-2 focus:ring-primary/20 bg-slate-50/50" 
                     placeholder="@handle" 
                     value={formData.socials.twitter}
                     onChange={e => setFormData({ ...formData, socials: { ...formData.socials, twitter: e.target.value } })}
                   />
                 </div>
                 <div className="space-y-2">
                   <label className="text-xs font-bold uppercase text-slate-500">Instagram</label>
                   <input 
                     type="text" 
                     className="w-full rounded-xl border border-slate-200 p-3 text-sm focus:ring-2 focus:ring-primary/20 bg-slate-50/50" 
                     placeholder="@handle" 
                     value={formData.socials.instagram}
                     onChange={e => setFormData({ ...formData, socials: { ...formData.socials, instagram: e.target.value } })}
                   />
                 </div>
               </div>
            </div>

            {/* Additional Notes */}
            <div className="space-y-2">
              <label className="text-xs font-bold uppercase text-slate-500">Special Notes</label>
              <textarea 
                className="w-full rounded-xl border border-slate-200 p-3 text-sm focus:ring-2 focus:ring-primary/20 bg-slate-50/50 min-h-[60px]" 
                placeholder="Any other relevant context for this brand..." 
                value={formData.notes}
                onChange={e => setFormData({ ...formData, notes: e.target.value })}
              />
            </div>

            <div className="flex justify-end gap-3 pt-6 border-t border-slate-50">
              <Button variant="ghost" type="button" onClick={() => {
                setIsModalOpen(false);
                setEditingBrand(null);
              }} className="font-bold">Cancel</Button>
              <Button type="submit" loading={createBrand.isPending || updateBrand.isPending} className="font-black uppercase tracking-tight shadow-xl shadow-primary/20">
                {editingBrand ? "Apply Global Updates" : "Register Brand Entity"}
              </Button>
            </div>
          </form>

          {/* Real-time Preview */}
          <div className="hidden lg:block space-y-4">
             <h4 className="text-[10px] font-black uppercase tracking-widest text-slate-400">Live Card Preview</h4>
             <Card 
               className="p-0 overflow-hidden flex flex-col shadow-2xl border-slate-200 scale-95 origin-top transition-all"
               style={{ boxShadow: `0 25px 50px -12px ${formData.color}20` }}
             >
                <div className="h-28 relative" style={{ backgroundColor: formData.color }}>
                  <div className="absolute inset-0 bg-gradient-to-br from-black/20 to-transparent" />
                  {formData.logo && (
                    <div className="absolute -bottom-6 left-6 h-16 w-16 rounded-2xl bg-white p-2 shadow-xl border border-slate-100 flex items-center justify-center">
                      <img src={formData.logo} alt="Preview" className="max-h-full max-w-full object-contain" referrerPolicy="no-referrer" />
                    </div>
                  )}
                </div>
                <div className="p-6 pt-10 space-y-3">
                  <div>
                    <h4 className="text-lg font-black text-slate-900 leading-tight truncate">{formData.name || 'Brand Name'}</h4>
                    <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest truncate">{formData.tagline || 'Tagline placeholder'}</p>
                  </div>
                  <p className="text-[11px] text-slate-500 line-clamp-3 leading-relaxed">
                    {formData.description || 'Your brand description will appear here as you type. It helps team members understand the core identity.'}
                  </p>
                  <div className="flex gap-1.5 pt-2 text-slate-900">
                     <div className="h-4 w-4 rounded-full border border-white shadow-sm" style={{ backgroundColor: formData.color }} />
                     <div className="h-4 w-4 rounded-full border border-white shadow-sm" style={{ backgroundColor: formData.secondaryColor }} />
                  </div>
                </div>
             </Card>

             <div className="p-4 rounded-xl bg-slate-50 border border-slate-100 space-y-3">
                <div className="flex items-center gap-2 text-slate-500">
                   <Info className="h-3.5 w-3.5" />
                   <span className="text-[10px] font-bold uppercase">Dynamic Assets</span>
                </div>
                <p className="text-[10px] text-slate-400 leading-relaxed">
                  The primary color will be used for task cards, project grouping, and chart segments across the entire Brivo suite.
                </p>
             </div>
          </div>
        </div>
      </Modal>

      <Modal 
        isOpen={isDeleteModalOpen} 
        onClose={() => setIsDeleteModalOpen(false)} 
        title="Permanently remove brand?"
      >
        <div className="space-y-4">
          <div className="p-4 rounded-xl bg-red-50 border border-red-100 flex gap-3">
             <AlertTriangle className="h-5 w-5 text-red-500 shrink-0" />
             <div className="space-y-1 text-slate-900">
               <p className="text-xs text-red-700 font-bold uppercase transition-widest tracking-widest">Critical Warning</p>
               <p className="text-xs text-red-700 leading-relaxed">
De-registering <span className="font-bold underline">{brandToDelete?.name}</span> will remove all associated metadata, social links, and the visual palette. This action is irreversible.
               </p>
             </div>
          </div>
          <div className="flex justify-end gap-3 pt-4">
            <Button variant="ghost" onClick={() => setIsDeleteModalOpen(false)} className="font-bold">Abort</Button>
            <Button 
              variant="secondary" 
              className="bg-red-500 hover:bg-red-600 text-white font-black" 
              loading={deleteBrand.isPending}
              onClick={() => {
                deleteBrand.mutate(brandToDelete._id, {
                  onSuccess: () => setIsDeleteModalOpen(false)
                });
              }}
            >
              Confirm Deletion
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
